### ISSUE TITLE
[FORUMS] Discussion forums issues

### ISSUE THREAD

**Issue by nyenye** [osTicket/docs#31]
Sorry to open the issue here, but couldn't find a repo for the website, and I figured that opening it on the main product repo, would be worse.

First of all I wanted to ask a question on the forums, and well the experience was pretty bad. First I created the account, and the confirmation email was sent to spam by GMail.

Second, even thought I was logged in, with the email confirmed, I can't figure out how to post a question. I'm starting to guess that I need to have and account with X time before posting.

Last, whenever I try to open the profile of a user, mine included, it displays a 404 page.

That sums up my experience. If anyone could clarify my second point, I'd be very thankful.

**Comment by JediKev** [comment]
@nyenye 

There is an Account Approval process that occurs before you can post discussions. We are addressing this issue by placing a banner when you create an account letting you know so when we switch forum platforms soon.

As for the spam issue, we'll look into it.

I have never experienced 404 errors but we have had issues with the site recently (which is why we are moving away from it).

PLEASE do not post stuff like this on here (ESPECIALLY on the Docs issues; as it's not related to Docs). Instead you should send an email to `help@osticket.com`.

Cheers.

**Comment by nyenye** [comment]
Hey thanks for the info, and yeah I knew it was a bad idea to post it here. Sorry about that.
